import { dateToString } from '../../../utils/formatter';
const initCustomer = {
  dinpdate: dateToString(new Date()),
  ccusid: '',
  cinitial: '',
  cchnl: '',
  ccurcode: '',
  lmember: '',
  ccusnam: '',
  lactive: '',
  cnpwp: '',
  cnppkp: '',
  cstreet: '',
  cstreet2: '',
  czip: '',
  ckota: '',
  cstate: '',
  cemail: '',
  cnotelp: '',
  cnohp: '',
  cfax: '',
  cremark: '',
  liscorcus: '',
  ccorcusid: '',
  cshpcode: '',
  cshpname: '',
  luseshpto: '',
  cshptoname: '',
  cshptoadr1: '',
  cshptoadr2: '',
  cshptokota: '',
  cshptoup: '',
  nduedays: 0,
  ndueallow: 0,
  npctdisc: 0.0,
  lppn: '',
  ccpcode: '',
  cdefwhseid: '',
  csalesid: '',
  nmaxcredit: 0.0,
  cacctslshp: '',
  cacctslret: '',
  cacctar: '',
  cacctslsdp: '',
};

export default initCustomer;
