import { dateToString } from '../../../utils/formatter';
export const BSODHEAD = {
  dsodate: dateToString(new Date()),
  csonum: '?',
  dneeddate: null,
  cremark: '',
  customer: {
    ccusid: '',
    cinitial: '',
    cnotelp: '',
    cemail: '',
  },
  ccustpo: '?',
  cshpcode: '',
  cshpname: '',
  cshptoname: '',
  cshptoadr1: '',
  cshptoadr2: '',
  cshptokota: '',
  cshptoup: '',
  cpaytrm: '',
  ndp: '',
  nduedays: '',
  npctdisc: '',
  npctppn: '',
  namount: '',
  ddate1: '',
  ddate2: '',
  cwhseid: '',
  csalesid: '',
  csofoot1: '',
  csofoot2: '',
  csofoot3: '',
};

export const BSODITEM = {
  nline: '',
  crefnote: '',
  cstocode: '',
  cstoname: '',
  csize: '',
  cloc: '',
  ncso: '',
  nqso: 0,
  cuom: '',
  nhrgjua: 0,
  cdsset: '',
  cdisc: '',
  ndisc: 0,
  nrpdisc: 0,
  cautuser: '',
  npctkomisi: '',
  cuomkom: '',
};
