export const BSOFHEAD = {
  DSODATE: 'dsodate',
  CSONUM: 'csonum',
  DNEEDDATE: 'dneeddate',
  CREMARK: 'cremark',
  CUSTOMER: {
    AS: 'customer',
    _: {
      CCUSID: 'ccusid',
      CINITIAL: 'cinitial',
      CNOTELP: 'cnotelp',
      CEMAIL: 'cemail',
    },
  },
  CCUSTPO: 'ccustpo',
  CSHPCODE: 'cshpcode',
  CSHPNAME: 'cshpname',
  CSHPTONAME: 'cshptoname',
  CSHPTOADR1: 'cshptoadr1',
  CSHPTOADR2: 'cshptoadr2',
  CSHPTOKOTA: 'cshptokota',
  CSHPTOUP: 'cshptoup',
  CPAYTRM: 'cpaytrm',
  NDP: 'ndp',
  NDUEDAYS: 'nduedays',
  NPCTDISC: 'npctdisc',
  NPCTPPN: 'npctppn',
  NAMOUNT: 'namount',
  DDATE1: 'ddate1',
  DDATE2: 'ddate2',
  CWHSEID: 'cwhseid',
  CSALESID: 'csalesid',
  CSOFOOT1: 'csofoot1',
  CSOFOOT2: 'csofoot2',
  CSOFOOT3: 'csofoot3',
};

export const BSOFITEM = {
  NLINE: 'nline',
  CREFNOTE: 'crefnote',
  CSTOCODE: 'cstocode',
  CSTONAME: 'cstoname',
  CSIZE: 'csize',
  CLOC: 'cloc',
  NCSO: 'ncso',
  NQSO: 'nqso',
  CUOM: 'cuom',
  NHRGJUA: 'nhrgjua',
  CDISC: 'cdisc',
  NDISC: 'ndisc',
  NRPDISC: 'nrpdisc',
  CAUTUSER: 'cautuser',
  NPCTKOMISI: 'npctkomisi',
  NKOMISI: 'nkomisi',
  CUOMKOM: 'cuomkom',
  NQSOORG: 'nqsoorg',
  NQSJORG: 'nqsjorg',
  NQSHIPORG: 'nqshiporg',
  NQRJORG: 'nqrjorg',
  NQINVORG: 'nqinvorg',
  NQCMORG: 'nqcmorg',
};
